// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum GovernanceType {
  NONE,
  DEMOCRACY
}

enum ActionType {
  NONE,
  ATTACK_ONE,
  ATTACK_TWO,
  ATTACK_THREE,
  HEAL,
  TAUNT
}
