// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ActionType } from "./../Types.sol";

interface IVoteSystem {
  function moving_castles_VoteSystem_vote(ActionType _action) external;
}
